export const SET_CITY = `SET_CITY`;

export const SET_OFFER = `SET_OFFER`;
export const SET_COMMENTS = `SET_COMMENTS`;
export const SET_OFFERS = `SET_OFFERS`;
export const SET_NEARBY_OFFERS = `SET_NEARBY_OFFERS`;
export const SET_SORTING = `SET_SORTING`;

export const REQUIRE_AUTHORIZATION = `REQUIRE_AUTHORIZATION`;

